<?php

namespace Digitalwert\Symfony2\Bundle\Monodi\CommonBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Gedmo\Tree\Entity\Repository\NestedTreeRepository;

/**
 * FolderRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FolderRepository 
  extends NestedTreeRepository
{
    /**
     * Gibt einen QueryBuilder mit der eingeschränkten auswahl für DocumentFormType zurück
     *  
     * @return \Doctrine\ORM\QueryBuilder
     */
    public function createQueryBuilderForDocumentFormTypeChoice() {
       return $this->createQueryBuilder('f')
         ->where('f.lvl >= 2')
         ->orderBy('f.slug', 'ASC')
       ;
    }
}
