<?php

namespace Digitalwert\Symfony2\Bundle\Monodi\CommonBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * VersionControlSystemReposRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VersionControlSystemReposRepository extends EntityRepository
{
}
