<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20130503104413 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("CREATE TABLE ext_translations (id INT AUTO_INCREMENT NOT NULL, locale VARCHAR(8) NOT NULL, object_class VARCHAR(255) NOT NULL, field VARCHAR(32) NOT NULL, foreign_key VARCHAR(64) NOT NULL, content LONGTEXT DEFAULT NULL, INDEX translations_lookup_idx (locale, object_class, foreign_key), UNIQUE INDEX lookup_unique_idx (locale, object_class, field, foreign_key), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
        $this->addSql("CREATE TABLE ext_log_entries (id INT AUTO_INCREMENT NOT NULL, action VARCHAR(8) NOT NULL, logged_at DATETIME NOT NULL, object_id VARCHAR(32) DEFAULT NULL, object_class VARCHAR(255) NOT NULL, version INT NOT NULL, data LONGTEXT DEFAULT NULL COMMENT '(DC2Type:array)', username VARCHAR(255) DEFAULT NULL, INDEX log_class_lookup_idx (object_class), INDEX log_date_lookup_idx (logged_at), INDEX log_user_lookup_idx (username), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
        $this->addSql("ALTER TABLE monodi_document DROP INDEX UNIQ_C0263BF87E3C61F9, ADD INDEX IDX_C0263BF87E3C61F9 (owner_id)");
        $this->addSql("ALTER TABLE monodi_document DROP INDEX UNIQ_C0263BF8FE54D947, ADD INDEX IDX_C0263BF8FE54D947 (group_id)");
        $this->addSql("ALTER TABLE monodi_document DROP INDEX UNIQ_C0263BF86995AC4C, ADD INDEX IDX_C0263BF86995AC4C (editor_id)");
        $this->addSql("ALTER TABLE monodi_document ADD folder_id INT DEFAULT NULL");
        $this->addSql("ALTER TABLE monodi_document ADD CONSTRAINT FK_C0263BF8162CB942 FOREIGN KEY (folder_id) REFERENCES monodi_folder (id)");
        $this->addSql("CREATE INDEX IDX_C0263BF8162CB942 ON monodi_document (folder_id)");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("DROP TABLE ext_translations");
        $this->addSql("DROP TABLE ext_log_entries");
        $this->addSql("ALTER TABLE monodi_document DROP INDEX IDX_C0263BF87E3C61F9, ADD UNIQUE INDEX UNIQ_C0263BF87E3C61F9 (owner_id)");
        $this->addSql("ALTER TABLE monodi_document DROP INDEX IDX_C0263BF8FE54D947, ADD UNIQUE INDEX UNIQ_C0263BF8FE54D947 (group_id)");
        $this->addSql("ALTER TABLE monodi_document DROP INDEX IDX_C0263BF86995AC4C, ADD UNIQUE INDEX UNIQ_C0263BF86995AC4C (editor_id)");
        $this->addSql("ALTER TABLE monodi_document DROP FOREIGN KEY FK_C0263BF8162CB942");
        $this->addSql("DROP INDEX IDX_C0263BF8162CB942 ON monodi_document");
        $this->addSql("ALTER TABLE monodi_document DROP folder_id");
    }
}
