<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20130429131045 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("CREATE TABLE monodi_folder (id INT AUTO_INCREMENT NOT NULL, parent_id INT DEFAULT NULL, title VARCHAR(255) NOT NULL, slug VARCHAR(255) NOT NULL, lft INT NOT NULL, rgt INT NOT NULL, lvl INT NOT NULL, createdAt DATETIME NOT NULL, updatedAt DATETIME NOT NULL, UNIQUE INDEX UNIQ_78F5B710989D9B62 (slug), INDEX IDX_78F5B710727ACA70 (parent_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
        $this->addSql("ALTER TABLE monodi_folder ADD CONSTRAINT FK_78F5B710727ACA70 FOREIGN KEY (parent_id) REFERENCES monodi_folder (id) ON DELETE SET NULL");
        $this->addSql("ALTER TABLE monodi_document ADD owner_id INT DEFAULT NULL, ADD group_id INT DEFAULT NULL, ADD editor_id INT DEFAULT NULL");
        $this->addSql("ALTER TABLE monodi_document ADD CONSTRAINT FK_C0263BF87E3C61F9 FOREIGN KEY (owner_id) REFERENCES fos_user (id)");
        $this->addSql("ALTER TABLE monodi_document ADD CONSTRAINT FK_C0263BF8FE54D947 FOREIGN KEY (group_id) REFERENCES fos_group (id)");
        $this->addSql("ALTER TABLE monodi_document ADD CONSTRAINT FK_C0263BF86995AC4C FOREIGN KEY (editor_id) REFERENCES fos_user (id)");
        $this->addSql("CREATE UNIQUE INDEX UNIQ_C0263BF87E3C61F9 ON monodi_document (owner_id)");
        $this->addSql("CREATE UNIQUE INDEX UNIQ_C0263BF8FE54D947 ON monodi_document (group_id)");
        $this->addSql("CREATE UNIQUE INDEX UNIQ_C0263BF86995AC4C ON monodi_document (editor_id)");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("ALTER TABLE monodi_folder DROP FOREIGN KEY FK_78F5B710727ACA70");
        $this->addSql("DROP TABLE monodi_folder");
        $this->addSql("ALTER TABLE monodi_document DROP FOREIGN KEY FK_C0263BF87E3C61F9");
        $this->addSql("ALTER TABLE monodi_document DROP FOREIGN KEY FK_C0263BF8FE54D947");
        $this->addSql("ALTER TABLE monodi_document DROP FOREIGN KEY FK_C0263BF86995AC4C");
        $this->addSql("DROP INDEX UNIQ_C0263BF87E3C61F9 ON monodi_document");
        $this->addSql("DROP INDEX UNIQ_C0263BF8FE54D947 ON monodi_document");
        $this->addSql("DROP INDEX UNIQ_C0263BF86995AC4C ON monodi_document");
        $this->addSql("ALTER TABLE monodi_document DROP owner_id, DROP group_id, DROP editor_id");
    }
}
