parameters:
    database_driver: pdo_mysql
    database_host: 127.0.0.1
    database_port: null
    database_name: symfony2_monodi
    database_user: root
    database_password: 68M4ZLQHrbD6WjZA
    mailer_transport: smtp
    mailer_host: 127.0.0.1
    mailer_user: null
    mailer_password: null
    locale: en
    secret: e2669818e3134c10add6bdfec1a65c90d
    database_path: null
    monodi_git_remote_uri: "ssh://petzold@adwserv9.adwmainz.net:7022/var/git/test.git"
    monodi_existdb_uri: "https://adwserv9.adwmainz.net/exist/rest/db/"
    monodi_existdb_username: monodi
    monodi_existdb_password: tLZ5BölTwq!qdUög
