digitalwert_monodi_admin:
    resource: "@DigitalwertMonodiAdminBundle/Controller/"
    type:     annotation
    prefix:   /admin

digitalwert_monodi_frontend:
    resource: "@DigitalwertMonodiFrontendBundle/Controller/"
    type:     annotation
    prefix:   /
    
digitalwert_monodi_client:
    resource: "@DigitalwertMonodiClientBundle/Controller/"
    type:     annotation
    prefix:   /client

#digitalwert_monodi_api_document:
#    resource: Digitalwert\Symfony2\Bundle\Monodi\ApiBundle\Controller\DocumentController
#    type:     rest
#    prefix:   /api/v1/documents

digitalwert_monodi_api:
    resource: "@DigitalwertMonodiApiBundle/Controller/"
    type:     annotation
    prefix:   /api/v1
    
NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /api/doc

#digitalwert_monodi_common:
#    resource: "@DigitalwertMonodiCommonBundle/Controller/"
#    type:     annotation
#    prefix:   /

#
# User
fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile
#
# OAUTH
fos_oauth_server_token:
    resource: "@FOSOAuthServerBundle/Resources/config/routing/token.xml"

fos_oauth_server_authorize:
    resource: "@FOSOAuthServerBundle/Resources/config/routing/authorize.xml"
    
digitalwert_monodi_oauth_server_security:
#    resource: "@AcmeOAuthServerBundle/Resources/config/routing/security.xml"
    resource: "@DigitalwertMonodiOAuthServerBundle/Controller/"
    type:     annotation
    prefix: /
